<?php

/**
 * @file
 * A global views field that provides site's base url.
 */

/**
 * Implements hook_views_api().
 */
function views_base_url_views_api() {
  return array(
    'api' => 3,
    'path' => backdrop_get_path('module', 'views_base_url') . '/includes/views',
  );
}



/**
 * Implements hook_autoload_info().
 */
function views_base_url_autoload_info() {
  return array(
    'ViewsBaseUrlHandlerBaseUrl' => 'includes/views/handlers/views_base_url_handler_base_url.inc',
  );
}